### ISSUE TITLE
Map print pdf won't open in Adobe Reader or Adobe Acrobat

### ISSUE THREAD

**Issue by d3netxer** [GeoNode/geonode-client#109]
Tested with Adobe Reader XI version 11.0.18

and

Adobe X ver 10.1.15

and received the same error:

There was an error processing a page. There was a problem reading this document (110).

Google Chrome can open the .pdf however

**Comment by bartvde** [comment]
might be related to https://github.com/MrRio/jsPDF/issues/862

**Comment by bartvde** [comment]
For now we can move back to jpeg I guess, I've confirmed that works

**Comment by bartvde** [comment]
Fixed with https://github.com/boundlessgeo/sdk/commit/6d7f39294684cdd4d2c08aa063bacbd3217f5a9d

**Comment by bartvde** [comment]
Pulled in with sdk upgrade here: https://github.com/GeoNode/geonode-client/pull/139
