### ISSUE TITLE
Table not keeping selections

### ISSUE THREAD

**Issue by d3netxer** [GeoNode/geonode-client#110]
In this map: http://2c.terranodo.io/maps/1/view#map=38.21851414258813/4038980.2/6443231.82/0 

if I view the table of a layer and make some selections and then go to options; it clears out all of the selections I made from the table. 

I tried the same thing on a similar map with just one layer and it works fine:  http://2c.terranodo.io/maps/309/view#map=9.554628535647032/9350424.31/3275473.54/0

**Comment by bartvde** [comment]
I can reproduce, will investigate

**Comment by bartvde** [comment]
it seems the table component gets recreated and hence loses its state

Maybe this is because we couldn't have the pureRender decorator on the table

**Comment by bartvde** [comment]
No this is because the data is retrieved again, and so the new feature is not in the selected array since it's not the exact same feature. We used to have this check based on fid, but not all datasets have stable fids

**Comment by bartvde** [comment]
Just thinking now, this fix might only work for sources with real feature ids, since the ol3 vector source filters those out as duplicates. If the dataset has uuid type fids, it might not work. Not sure how common this is in a GeoNode environment
