### ISSUE TITLE
print can still come up with empty map

### ISSUE THREAD

**Issue by bartvde** [GeoNode/geonode-client#133]
It seems CORS errors in maps like:

http://localhost:8000/maps/5#map=2445.98490512564/-17336795.06/8443616.49/0

but not in maps/new where I add a local layer

**Comment by bartvde** [comment]
ah it's because when creating from MapConfig, crossOrigin: anonymous is used so CORS is needed

when adding layer through add layer dialog this is not the case, and hence the print fails then because the source has not been amended

**Comment by bartvde** [comment]
should be fixed with https://github.com/boundlessgeo/sdk/commit/9de244543f74715363158e010bc261609a9bd54e

**Comment by bartvde** [comment]
Pulled in with sdk upgrade here: https://github.com/GeoNode/geonode-client/pull/139

**Comment by milafrerichs** [comment]
works on the layer detail page, but not on the map pages.

**Comment by bartvde** [comment]
Problem was with the Esri BaseMap, should be fixed with: https://github.com/boundlessgeo/sdk/commit/b7f704573c8366349fc5cb9e2771090c48c15596

**Comment by bartvde** [comment]
Fixed with sdk upgrade
