### ISSUE TITLE
redundant button in Add Layers window

### ISSUE THREAD

**Issue by schignel** [GeoNode/geonode-client#137]
These two buttons both select the layer--seems like they should either look the same, or do different things, or there should just be one of them to avoid confusion.

![image](https://cloud.githubusercontent.com/assets/19474876/22379125/4fa1bd64-e475-11e6-97e2-dffbab00f99b.png)

**Comment by jj0hns0n** [comment]
Im wondering if the one on the right might be used to add the ayer to the
map directly and zoom? I realize that requires adding it too.

**Comment by bartvde** [comment]
it's not a button, it's just an icon depicting if it's a group or a single layer. The whole row / listitem actually selects.

**Comment by bartvde** [comment]
I'll get rid of the icons, they don't add much value anyway

**Comment by bartvde** [comment]
Removed them with: https://github.com/boundlessgeo/sdk/commit/5c9f0f82a2630b0c9c1e8675c9cd1f82c4ef7e04 will be pulled in with the next sdk release

**Comment by bartvde** [comment]
Pulled in with sdk upgrade here: https://github.com/GeoNode/geonode-client/pull/139
