### ISSUE TITLE
Users are unable to make style changes to layers.

### ISSUE THREAD

**Issue by BerryDaniel** [GeoNode/geonode-client#145]
https://github.com/GeoNode/geonode/blob/master/geonode/layers/templates/layers/layer_detail.html#L340

The template only exposes editing and managing styles if geoext (ol2) is enabled.

@bartvde is this being worked on?

**Comment by bartvde** [comment]
no I don't think this is being worked on, this is new to me

@jj0hns0n @milafrerichs so is this something that we need to add in geonode-client I guess?
