### ISSUE TITLE
layers button goes over navigation bar when scrolling

### ISSUE THREAD

**Issue by francbartoli** [GeoNode/geonode-client#167]
This happens in geonode as in the screenshot
![layers_button](https://cloud.githubusercontent.com/assets/560676/22976992/4890807e-f38d-11e6-9e9b-dcf40dcd931c.png)

**Comment by bartvde** [comment]
This has been resolved a while ago, what version are you on?

**Comment by francbartoli** [comment]
sorry @bartvde not as recent as expected. Going to close this.
