### ISSUE TITLE
Handle for Layer Names that are longer than the Identify popup

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode-client#37]
<img width="1551" alt="screen shot 2016-10-27 at 10 12 29" src="https://cloud.githubusercontent.com/assets/506078/19777621/f4c04e4a-9c2d-11e6-96ad-1ebf603c4b1f.png">

**Comment by bartvde** [comment]
Has been fixed in the SDK, needs to be pulled in only

**Comment by bartvde** [comment]
See: https://github.com/boundlessgeo/sdk/issues/230

**Comment by bartvde** [comment]
Fixed with https://github.com/GeoNode/viewer/pull/42/commits/810c4611758292e6c0bdcd18eed3fc9d61e9dedd
