### ISSUE TITLE
remove deleting layers

### ISSUE THREAD

**Issue by milafrerichs** [GeoNode/geonode-client#40]

**Comment by bartvde** [comment]
This was done but needs an sdk release

**Comment by bartvde** [comment]
See: https://github.com/GeoNode/viewer/commit/659b334f2164804e2dc15fe09ad138421ae3cc8b

**Comment by bartvde** [comment]
Done with https://github.com/GeoNode/viewer/pull/42/commits/810c4611758292e6c0bdcd18eed3fc9d61e9dedd
