### ISSUE TITLE
Integrate Layer List and Legend

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode-client#45]
The Layer List and Legend should be in the same panel. 

<img width="1538" alt="screen shot 2016-10-31 at 14 46 44" src="https://cloud.githubusercontent.com/assets/506078/19872824/eaa501e6-9f78-11e6-9de6-51dec062e1bd.png">

**Comment by jj0hns0n** [comment]
Didnt intend for my screenshot to include the Identify ... but could be interesting to expand the layer to see the attributes here in a single menu.

**Comment by bartvde** [comment]
You mean legend and layer list should be a single component, like it was in GXP layer trees? The GXP based viewer in GeoNode also has a separate legend btw.

**Comment by jj0hns0n** [comment]
Yep, it is preferable to have this in a single panel and not separate (as
in GXP layer trees). Strangely, I dont see the legend at all in the current
instance on demo.geonode.org/maps/new ... but I _thought_ this was
integrated into the panel already long ago.

**Comment by bartvde** [comment]
in the composer yes, in the viewer it is separate? http://geosm.adpc.net/maps/190

![screen shot 2016-11-01 at 16 52 23](https://cloud.githubusercontent.com/assets/319678/19896152/96194f70-a053-11e6-886f-15a4c8aa46f1.png)

**Comment by bartvde** [comment]
But I'll see if it's feasible to integrate it in the new viewer

**Comment by jj0hns0n** [comment]
Thats in the map detail page. Its integrated in the map viewer (works here,
didnt see it on the demo.geonode.org)

http://geosm.adpc.net/maps/190/view

[image: Inline image 1]

**Comment by bartvde** [comment]
What you call map viewer, is what I call composer ;-)
But indeed, I think we are on the same page then.

But you want it integrated in both viewer and composer right?

**Comment by bartvde** [comment]
Done in SDK with: https://github.com/boundlessgeo/sdk/commit/18a01eff910841305c859eeec183759e5c5039f8
