### ISSUE TITLE
Move Right Hand menu to the top of the map

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode-client#47]
<img width="1539" alt="screen shot 2016-10-31 at 14 50 41" src="https://cloud.githubusercontent.com/assets/506078/19872934/7636f566-9f79-11e6-8723-bcf651ab7e6c.png">

**Comment by bartvde** [comment]
The space is for the north array that shows up only when the map is rotated, but maybe this should be different? Suggestions welcome.

**Comment by jj0hns0n** [comment]
I suppose it should always be shown or moved to the top ... or perhaps to
the other side with the rest of the navigation buttons.
