### ISSUE TITLE
Use Background layers from Settings file

### ISSUE THREAD

**Issue by milafrerichs** [GeoNode/geonode-client#94]

**Comment by bartvde** [comment]
I'm noticing we have some more issues here that need fixing. I added all base layers that geonode has settings for.

All those base layers end up in the layer list base layer group. Since we have the add basemap function instead, the layer list should only show the visible base layer in this case.

**Comment by bartvde** [comment]
Getting slowly there:

![selection_069](https://cloud.githubusercontent.com/assets/319678/22625444/6434c9c8-eb97-11e6-8a2b-b1dda6c484c8.png)

**Comment by bartvde** [comment]
Related sdk change is here: https://github.com/boundlessgeo/sdk/commit/e31e30c0acb64e2b8b7d151c74d61ddc0bb5af7b

Still need to work on omitting those base map layers from the LayerList

**Comment by bartvde** [comment]
Last issue resolved with: https://github.com/boundlessgeo/sdk/commit/f9472a854086cc6bf909c4bedc389b2b43c99e96
